version: '3'

services:
  web:
    build: .
    ports:
      - "8035:8035"
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: dev-user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dev_db
    ports:
      - 5432:5432
    expose:
      - "5432"
    volumes:
      - db-data:/var/lib/postgresql/data:cached

  test-postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: test-user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test_db
    ports:
      - 5434:5432 # Use a different port to avoid conflicts with the main database
    expose:
      - "5434" # Exposing the different port for clarity
    volumes:
      - test-db-data:/var/lib/postgresql/data:cached

volumes:
  db-data:
  test-db-data: