version: '3'

services:
  web:
    build: .
    ports:
      - "8035:8035"
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: on-failure
    environment:
      POSTGRES_DB: library_dev
      POSTGRES_USER: library_user
      POSTGRES_PASSWORD: library_user
    ports:
      - "5432:5432"
