version: '3'

services:
  backend:
    image: 'mouralucas/rolf-services:library'
    build: .
    ports:
      - "9001:9001"
    depends_on:
      - "pg_library_service"

  pg_library_service:
    container_name: 'pg_library_service'
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: dev-user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: library_dev_db
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - db-data:/var/lib/postgresql/data:cached

volumes:
  db-data: