extend type Query {
    getAuthors(params: GetAuthorsRequest): GetAuthorsResponse!
    getSeries: GetSerieResponse!
    getCollections: GetCollectionResponse!
    getPublishers: GetPublishersResponse!
    getLanguages: GetLanguagesResponse!
    getCountries: GetCountryResponse!
    getStatus(params: GetStatusInput): GetStatusResponse!
}

extend type Mutation {
    createAuthor(author: CreateAuthorInput): CreateAuthorResponse!
    createSerie(serie: CreateSerieRequest): CreateSerieResponse!
    createCollection(collection: CreateCollectionRequest): CreateCollectionResponse!
    createPublisher(publihser: CreatePublisherRequest): CreatePublisherResponse!
    createLanguage(language: CreateLanguageRequest): CreateLanguageResponse!
    createCountry(country: CreateCountryRequest): CreateCountryResponse!
}


input OrderByInput {
    field: String!
    direction: String
}

# Author schemas
input GetAuthorsRequest {
    authorId: Int
}

type GetAuthorsResponse {
    quantity: Int!
    authors: [Author]!
}

input CreateAuthorInput {
    id: Int
    name: String!
    countryId: String
    languageId: String
    birthDate: String
    description: String
    isTranslator: Boolean = False
}

type CreateAuthorResponse  {
    author: Author!
}

type Author {
    id: Int!
    name: String!
    birthDate: String
    description: String
    countryId: String
    countryName: String
    languageId: String
    languageName: String
}

# Series schemas
type GetSerieResponse {
    quantity: Int!
    series: [Serie]!
}

input CreateSerieRequest {
    serieName: String!
}

type CreateSerieResponse {
    serie: Serie!
}

type Serie {
    id: Int!
    name: String!
    originalName: String
    description: String
    countryName: String
    order: Int
    itemType: String
}

# Collections schemas
type GetCollectionResponse {
    quantity: Int!
    collections: [Collection]!
}

input CreateCollectionRequest {
    collectionsName: String!
    description: String
}

type CreateCollectionResponse {
    collection: Collection
}

type Collection {
    id: Int!
    name: String!
    description: String
}

# Publishers schemas
type GetPublishersResponse {
    quantity: Int!
    publishers: [Publisher]!
}

input CreatePublisherRequest {
    publisherName: String!
    countryId: String
    description: String
    parentId: Int
}

type CreatePublisherResponse {
    publisher: Publisher
}

type Publisher{
    publisherId: Int!
    publisherName: String!
    description: String
    countryId: String
    countryName: String
    parentId: Int
}

# Language schemas
type GetLanguagesResponse {
    quantity: Int!
    languages: [Language]!
}

input CreateLanguageRequest {
    languageId: String!
    languageName: String!
    languageCode: String!
}

type CreateLanguageResponse {
    language: Language!
}

type Language {
    languageId: String!
    languageName: String!
    languageCode: String
}

# Country schemas
type GetCountryResponse {
    quantity: Int!
    countries: [Country]!
}

input CreateCountryRequest {
    countryId: String!
    countryName: String!
    continent: String!
    description: String
}

type CreateCountryResponse {
    country: Country!
}


type Country {
    countryId: String!
    countryName: String!
    continent: String
    description: String
}


# Status schemas
input GetStatusInput {
    statusType: String
}

type GetStatusResponse {
    quantity: Int!
    statuses: [Status]!
}

type Status {
    id: String!
    name: String!
    description: String
    order: Int
    statusType: String!
}