extend type Query {
  # Item queries
  getItem(id: Int!): Item
  getItems(params: GetItemInput): GetItemResponse
}

extend type Mutation {
    createItem(item: CreateItemInput): CreateItemResponse!
    updateItem(item: UpdateItemInput): CreateItemResponse!
}


# Item schemas
input GetItemInput {
  itemId: Int
  title: String
  mainAuthorId: Int
  itemTypeId: String
  orderBy: [OrderByInput]
}

type GetItemResponse {
    quantity: Int,
    items: [Item]
}

input CreateItemInput {
  itemId: Int
  lastStatusId: String!
  lastStatusDate: String!
  mainAuthorId: Int!
  authorsId: [Int]
  translatorId: Int
  otherAuthorsId: [Int]
  title: String!
  subtitle: String
  titleOriginal: String
  subtitleOriginal: String
  isbn: String
  isbn10: String
  itemTypeId: String
  pages: Int
  volume: Int
  edition: Int
  publicationDate: String
  originalPublicationDate: String
  serieId: Int
  collectionId: Int
  publisherId: Int
  formatId: String
  languageId: String
  coverPrice: Float
  paidPrice: Float
  dimensions: String
  height: Int
  width: Int
  thickness: Int
  summary: String
  observation: String
  cover: String
}

input UpdateItemInput {
  itemId: Int!
  lastStatusId: String
  lastStatusDate: String
  mainAuthorId: Int
  authorsId: [Int]
  translatorId: Int
  otherAuthorsId: [Int]
  title: String
  subtitle: String
  titleOriginal: String
  subtitleOriginal: String
  isbn: String
  isbn10: String
  itemTypeId: String
  pages: Int
  volume: Int
  edition: Int
  publicationDate: String
  originalPublicationDate: String
  serieId: Int
  collectionId: Int
  publisherId: Int
  formatId: String
  languageId: String
  coverPrice: Float
  paidPrice: Float
  dimensions: String
  height: Int
  width: Int
  thickness: Int
  summary: String
  observation: String
  cover: String
}

type CreateItemResponse {
  item: Item
}

type Item {
  id: Int!
  mainAuthorId: Int!
  mainAuthorName: String
  title: String!
  subtitle: String
  titleOriginal: String
  subtitleOriginal: String
  isbn: String
  isbn10: String
  itemTypeId: String
  pages: Int
  volume: Int
  edition: Int
  publicationDate: String
  originalPublicationDate: String
  serieId: Int
  serieName: String
  collectionId: Int
  collectionName: String
  publisherId: Int
  publisherName: String
  formatId: String
  languageId: String
  languageName: String
  coverPrice: Float
  paidPrice: Float
  dimensions: String
  height: Int
  width: Int
  thickness: Int
  summary: String
  observation: String
  lastStatusId: String
  lastStatusName: String
  lastStatusDate: String

  reading: Reading
}
