extend type Query {
  # Item queries
  getItem(id: Int!): Item
  getItems(params: GetItemInput): GetItemResponse
  getItemLocations: GetItemLocationResponse
  getItemsByLocation(params: GetItemsByLocationInput): [ItemsByLocation]!
}

extend type Mutation {
    createItem(item: CreateItemInput): CreateItemResponse!
    updateItem(item: UpdateItemInput): CreateItemResponse!
}


# Item schemas
input GetItemInput {
  itemId: Int
  title: String
  mainAuthorId: Int
  itemTypeId: String
  statusId: String
  orderBy: [OrderByInput]
}

type GetItemResponse {
    quantity: Int,
    items: [Item]
}

input CreateItemInput {
  id: Int
  lastStatusId: String!
  lastStatusDate: String!
  mainAuthorId: Int!
  authorsId: [Int]
  translatorId: Int
  otherAuthorsId: [Int]
  title: String!
  subtitle: String
  titleOriginal: String
  subtitleOriginal: String
  isbn: String
  isbn10: String
  itemTypeId: String
  pages: Int
  volume: Int
  edition: Int
  publicationDate: String
  originalPublicationDate: String
  serieId: Int
  collectionId: Int
  publisherId: Int
  formatId: String
  languageId: String
  coverPrice: Float
  paidPrice: Float
  summary: String
  observation: String
  cover: String
  locationId: Int!
}

input UpdateItemInput {
  id: Int!
  lastStatusId: String
  lastStatusDate: String
  mainAuthorId: Int
  authorsId: [Int]
  translatorId: Int
  otherAuthorsId: [Int]
  title: String
  subtitle: String
  titleOriginal: String
  subtitleOriginal: String
  isbn: String
  isbn10: String
  itemTypeId: String
  pages: Int
  volume: Int
  edition: Int
  publicationDate: String
  originalPublicationDate: String
  serieId: Int
  collectionId: Int
  publisherId: Int
  formatId: String
  languageId: String
  coverPrice: Float
  paidPrice: Float
  dimensions: String
  height: Int
  width: Int
  thickness: Int
  summary: String
  observation: String
  cover: String
  locationId: Int!
}

type CreateItemResponse {
  created: Boolean!
  id: Int!
  title: String!
}

type Item {
  id: Int!
  mainAuthorId: Int!
  mainAuthorName: String
  title: String!
  subtitle: String
  titleOriginal: String
  subtitleOriginal: String
  isbn: String
  isbn10: String
  itemTypeId: String
  pages: Int
  volume: Int
  edition: Int
  publicationDate: String
  originalPublicationDate: String
  serieId: Int
  serieName: String
  collectionId: Int
  collectionName: String
  publisherId: Int
  publisherName: String
  formatId: String
  languageId: String
  languageName: String
  coverPrice: Float
  cover: String
  paidPrice: Float
  summary: String
  observation: String
  lastStatusId: String
  locationId: Int
  lastStatusName: String
  lastStatusDate: String

  reading: Reading
}

# Item location
type GetItemLocationResponse {
  quantity: Int!
  locations: [ItemLocation]!
}

type ItemLocation {
  id: Int!
  name: String!
  physicalphysical_location: String
  description: String
}

input GetItemsByLocationInput {
  locationsIds: [Int]
}

type ItemsByLocation {
    locationId: Int!
    locationName: String!
    items: [Item]!
}