
extend type Query {
    # Reading queries
    getReading(reading_id: String!): GetReadingsResponse!
    getReadings(params: GetReadingsInput): GetReadingsResponse!
    getActiveReadings: GetActiveReadingsOutput!
    getReadingProgress(params: GetReadingProgressInput): GetReadingProgressOutput!
    getReadingStats(params: GetReadingStatsInput): GetReadingStatsResponse!

    getReadingGoals(params: GetReadingGoalsInput): GetReadingGoalsResponse!
}

extend type Mutation {
    # Reading mutations
    createReading(reading: CreateReadingInput!): CreateReadingOutput!
    createReadingProgress(progress: CreateReadingProgressInput!): CreateReadingProgressOutput!
}


# Reading schemas
input GetReadingsInput {
    itemId: Int
    readingId: String
    getProgress: Boolean
}

type GetReadingsResponse {
    quantity: Int!
    readings: [Reading!]
}

input CreateReadingInput {
    readingId: String
    itemId: Int!
    startDate: String!
    finishDate: String
    isDropped: Boolean = false
}


type CreateReadingOutput {
    created: Boolean!
    readingId: String!
}

type GetActiveReadingsOutput {
    quantity: Int!
    readings: [Reading]!
}

type Reading {
    id: String!
    itemId: Int!
    itemTitle: String
    item: Item!
    startDate: String!
    finishDate: String
    number: Int!
    active: Boolean
    statusId: String
    statusName: String
}

# Reading Progress schemas
input GetReadingProgressInput {
    readingId: String!
}

type GetReadingProgressOutput {
    quantity: Int!
    itemTitle: String
    pagesRead: String
    progress: [ReadingProgress]!
}

input CreateReadingProgressInput {
    readingId: String!
    progressType: String!
    value: Int
    progressDate: String
    rate: Int
    comment: String
}

type CreateReadingProgressOutput {
    created: Boolean!
    readingProgressId: String!
    itemTitle: String!
}

type ReadingProgress {
    id: String!
    reading: Reading!
    progressDate: String!
    page: Int
    percentage: Float
    rate: Int
    comment: String
}

# Reading status schemas
input GetReadingStatsInput {
    itemId: Int!
}

type GetReadingStatsResponse {
    stats: ReadingStats!
}

type ReadingStats {
    readingsCount: Int!
    lastReadingDate: String
    isCurrentlyReading: Boolean!
    currentReadingId: String
    currentPage: Int
    currentPercentage: Float
    lastReadings: [Reading]
}

# Reading goal schemas`
input GetReadingGoalsInput {
    year: Int
}

type GetReadingGoalsResponse {
    goals: [ReadingGoal]!
}

type ReadingGoal {
    id: String!
    item: Item!
    year: Int!
    acheived: Boolean
    dateAcheived: DateTime
}