"""Add nullable to code column in language

Revision ID: 0977ff5a475f
Revises: ab213cc9285a
Create Date: 2024-06-21 14:45:45.884940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '0977ff5a475f'
down_revision: Union[str, None] = 'ab213cc9285a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('language', 'code',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('language', 'code',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    # ### end Alembic commands ###
