"""Remove pk from item_id and author_id in item_author model

Revision ID: d99e6581709b
Revises: ed2969ff7d60
Create Date: 2024-11-25 22:32:15.223796

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d99e6581709b"
down_revision: Union[str, None] = "ed2969ff7d60"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
