"""Add item in reading progress

Revision ID: 817210d5584b
Revises: 218e5a2dbb9e
Create Date: 2024-07-25 09:14:13.633034

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "817210d5584b"
down_revision: Union[str, None] = "218e5a2dbb9e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "reading_progress", sa.Column("item_id", sa.Integer(), nullable=False)
    )
    op.create_foreign_key(None, "reading_progress", "item", ["item_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "reading_progress", type_="foreignkey")
    op.drop_column("reading_progress", "item_id")
    # ### end Alembic commands ###
