"""Add created_by

Revision ID: 4422d607d2f8
Revises: 817210d5584b
Create Date: 2024-08-07 16:54:52.656063

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4422d607d2f8"
down_revision: Union[str, None] = "817210d5584b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("author", sa.Column("created_by", sa.Uuid(), nullable=True))
    op.add_column("author", sa.Column("edited_by", sa.Uuid(), nullable=True))
    op.add_column("author", sa.Column("deleted_by", sa.Uuid(), nullable=True))
    op.add_column("collection", sa.Column("created_by", sa.Uuid(), nullable=True))
    op.add_column("collection", sa.Column("edited_by", sa.Uuid(), nullable=True))
    op.add_column("collection", sa.Column("deleted_by", sa.Uuid(), nullable=True))
    op.add_column("country", sa.Column("created_by", sa.Uuid(), nullable=True))
    op.add_column("country", sa.Column("edited_by", sa.Uuid(), nullable=True))
    op.add_column("country", sa.Column("deleted_by", sa.Uuid(), nullable=True))
    op.add_column("item", sa.Column("created_by", sa.Uuid(), nullable=True))
    op.add_column("item", sa.Column("edited_by", sa.Uuid(), nullable=True))
    op.add_column("item", sa.Column("deleted_by", sa.Uuid(), nullable=True))
    op.create_index(op.f("ix_item_title"), "item", ["title"], unique=False)
    op.add_column("item_author", sa.Column("created_by", sa.Uuid(), nullable=True))
    op.add_column("item_author", sa.Column("edited_by", sa.Uuid(), nullable=True))
    op.add_column("item_author", sa.Column("deleted_by", sa.Uuid(), nullable=True))
    op.add_column("item_status", sa.Column("created_by", sa.Uuid(), nullable=True))
    op.add_column("item_status", sa.Column("edited_by", sa.Uuid(), nullable=True))
    op.add_column("item_status", sa.Column("deleted_by", sa.Uuid(), nullable=True))
    op.add_column("language", sa.Column("created_by", sa.Uuid(), nullable=True))
    op.add_column("language", sa.Column("edited_by", sa.Uuid(), nullable=True))
    op.add_column("language", sa.Column("deleted_by", sa.Uuid(), nullable=True))
    op.add_column("publisher", sa.Column("created_by", sa.Uuid(), nullable=True))
    op.add_column("publisher", sa.Column("edited_by", sa.Uuid(), nullable=True))
    op.add_column("publisher", sa.Column("deleted_by", sa.Uuid(), nullable=True))
    op.add_column("reading", sa.Column("created_by", sa.Uuid(), nullable=True))
    op.add_column("reading", sa.Column("edited_by", sa.Uuid(), nullable=True))
    op.add_column("reading", sa.Column("deleted_by", sa.Uuid(), nullable=True))
    op.add_column("reading_progress", sa.Column("created_by", sa.Uuid(), nullable=True))
    op.add_column("reading_progress", sa.Column("edited_by", sa.Uuid(), nullable=True))
    op.add_column("reading_progress", sa.Column("deleted_by", sa.Uuid(), nullable=True))
    op.add_column("serie", sa.Column("created_by", sa.Uuid(), nullable=True))
    op.add_column("serie", sa.Column("edited_by", sa.Uuid(), nullable=True))
    op.add_column("serie", sa.Column("deleted_by", sa.Uuid(), nullable=True))
    op.add_column("status", sa.Column("created_by", sa.Uuid(), nullable=True))
    op.add_column("status", sa.Column("edited_by", sa.Uuid(), nullable=True))
    op.add_column("status", sa.Column("deleted_by", sa.Uuid(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("status", "deleted_by")
    op.drop_column("status", "edited_by")
    op.drop_column("status", "created_by")
    op.drop_column("serie", "deleted_by")
    op.drop_column("serie", "edited_by")
    op.drop_column("serie", "created_by")
    op.drop_column("reading_progress", "deleted_by")
    op.drop_column("reading_progress", "edited_by")
    op.drop_column("reading_progress", "created_by")
    op.drop_column("reading", "deleted_by")
    op.drop_column("reading", "edited_by")
    op.drop_column("reading", "created_by")
    op.drop_column("publisher", "deleted_by")
    op.drop_column("publisher", "edited_by")
    op.drop_column("publisher", "created_by")
    op.drop_column("language", "deleted_by")
    op.drop_column("language", "edited_by")
    op.drop_column("language", "created_by")
    op.drop_column("item_status", "deleted_by")
    op.drop_column("item_status", "edited_by")
    op.drop_column("item_status", "created_by")
    op.drop_column("item_author", "deleted_by")
    op.drop_column("item_author", "edited_by")
    op.drop_column("item_author", "created_by")
    op.drop_index(op.f("ix_item_title"), table_name="item")
    op.drop_column("item", "deleted_by")
    op.drop_column("item", "edited_by")
    op.drop_column("item", "created_by")
    op.drop_column("country", "deleted_by")
    op.drop_column("country", "edited_by")
    op.drop_column("country", "created_by")
    op.drop_column("collection", "deleted_by")
    op.drop_column("collection", "edited_by")
    op.drop_column("collection", "created_by")
    op.drop_column("author", "deleted_by")
    op.drop_column("author", "edited_by")
    op.drop_column("author", "created_by")
    # ### end Alembic commands ###
