"""Change name and type from isbn fields

Revision ID: b9cb39c28d18
Revises: 0977ff5a475f
Create Date: 2024-06-21 16:29:02.319588

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "b9cb39c28d18"
down_revision: Union[str, None] = "0977ff5a475f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("item", sa.Column("isbn", sa.String(), nullable=True))
    op.add_column("item", sa.Column("isbn10", sa.String(), nullable=True))
    op.drop_column("item", "isbn_formatted")
    op.drop_column("item", "isbn10_formatted")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "item",
        sa.Column("isbn10_formatted", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "item",
        sa.Column("isbn_formatted", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_column("item", "isbn10")
    op.drop_column("item", "isbn")
    # ### end Alembic commands ###
