"""Add serie to metadata and collection to edition model

Revision ID: 0849460c7dc6
Revises: 521f9ae33d51
Create Date: 2025-12-29 12:24:16.996932

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0849460c7dc6"
down_revision: Union[str, None] = "521f9ae33d51"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "item_edition", sa.Column("collection_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(None, "item_edition", "collection", ["collection_id"], ["id"])
    op.add_column("item_metadata", sa.Column("serie_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "item_metadata", "serie", ["serie_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "item_metadata", type_="foreignkey")
    op.drop_column("item_metadata", "serie_id")
    op.drop_constraint(None, "item_edition", type_="foreignkey")
    op.drop_column("item_edition", "collection_id")
    # ### end Alembic commands ###
