"""Adjust naming

Revision ID: aa12b9399c29
Revises: fd8f807eadf8
Create Date: 2025-12-21 22:55:24.891000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "aa12b9399c29"
down_revision: Union[str, None] = "fd8f807eadf8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("item_edition", sa.Column("format_id", sa.Uuid(), nullable=False))
    op.drop_constraint(
        op.f("item_edition_format_fkey"), "item_edition", type_="foreignkey"
    )
    op.create_foreign_key(None, "item_edition", "item_format", ["format_id"], ["id"])
    op.drop_column("item_edition", "format")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "item_edition",
        sa.Column("format", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "item_edition", type_="foreignkey")
    op.create_foreign_key(
        op.f("item_edition_format_fkey"),
        "item_edition",
        "item_format",
        ["format"],
        ["id"],
    )
    op.drop_column("item_edition", "format_id")
    # ### end Alembic commands ###
