"""Add serie relation to collections

Revision ID: b955e8847497
Revises: d99e6581709b
Create Date: 2025-07-19 10:26:24.189232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b955e8847497'
down_revision: Union[str, None] = 'd99e6581709b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection', sa.Column('serie', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'collection', 'serie', ['serie'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'collection', type_='foreignkey')
    op.drop_column('collection', 'serie')
    # ### end Alembic commands ###
