"""Adjust naming in UserItemEditionStatusModel

Revision ID: 521f9ae33d51
Revises: b4dcb6c593da
Create Date: 2025-12-23 14:24:24.583950

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "521f9ae33d51"
down_revision: Union[str, None] = "b4dcb6c593da"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("collection_serie_fkey"), "collection", type_="foreignkey")
    op.drop_column("collection", "serie")
    op.add_column("item_edition", sa.Column("pages", sa.Integer(), nullable=True))
    op.add_column(
        "user_item_edition_status",
        sa.Column("user_edition_id", sa.Uuid(), nullable=False),
    )
    op.drop_constraint(
        op.f("user_item_edition_status_edition_id_fkey"),
        "user_item_edition_status",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "user_item_edition_status",
        "user_item_edition",
        ["user_edition_id"],
        ["id"],
    )
    op.drop_column("user_item_edition_status", "edition_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_item_edition_status",
        sa.Column("edition_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "user_item_edition_status", type_="foreignkey")
    op.create_foreign_key(
        op.f("user_item_edition_status_edition_id_fkey"),
        "user_item_edition_status",
        "user_item_edition",
        ["edition_id"],
        ["id"],
    )
    op.drop_column("user_item_edition_status", "user_edition_id")
    op.drop_column("item_edition", "pages")
    op.add_column(
        "collection",
        sa.Column("serie", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        op.f("collection_serie_fkey"), "collection", "serie", ["serie"], ["id"]
    )
    # ### end Alembic commands ###
