"""Add nullable to fields

Revision ID: b4dcb6c593da
Revises: aa12b9399c29
Create Date: 2025-12-22 09:34:30.612075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4dcb6c593da'
down_revision: Union[str, None] = 'aa12b9399c29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('item_edition', 'subtitle',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('item_edition', 'isbn',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('item_edition', 'format_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('item_edition', 'format_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('item_edition', 'isbn',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('item_edition', 'subtitle',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
