"""Add serie to collecion

Revision ID: 503364eac02b
Revises: 89824d95d3de
Create Date: 2026-04-05 16:27:15.036395

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "503364eac02b"
down_revision: Union[str, None] = "89824d95d3de"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("collection", sa.Column("serie_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "collection", "serie", ["serie_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "collection", type_="foreignkey")
    op.drop_column("collection", "serie_id")
    # ### end Alembic commands ###
