"""Add reading goal model

Revision ID: e4902b5e16ce
Revises: a112cda298df
Create Date: 2026-03-09 21:20:23.019430

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "e4902b5e16ce"
down_revision: Union[str, None] = "a112cda298df"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reading_goal",
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("edited_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("edited_by", sa.Uuid(), nullable=True),
        sa.Column("deleted_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["item.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_column("item", "title_original")
    op.drop_column("item", "subtitle_original")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "item",
        sa.Column(
            "subtitle_original", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "item",
        sa.Column("title_original", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_table("reading_goal")
    # ### end Alembic commands ###
