"""Add acheived info to reading goal

Revision ID: 94e3ec305689
Revises: e4902b5e16ce
Create Date: 2026-03-17 21:16:44.674930

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "94e3ec305689"
down_revision: Union[str, None] = "e4902b5e16ce"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "reading_goal",
        sa.Column("achieved", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column("reading_goal", sa.Column("date_acheived", sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("reading_goal", "date_acheived")
    op.drop_column("reading_goal", "achieved")
    # ### end Alembic commands ###
