"""Remove item location

Revision ID: 3fd69c2a3513
Revises: 0a9b2e8d9c86
Create Date: 2026-02-14 19:49:56.632994

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3fd69c2a3513"
down_revision: Union[str, None] = "0a9b2e8d9c86"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("item_location_id_fkey"), "item", type_="foreignkey")
    op.drop_table("item_location")
    op.drop_column("item", "height")
    op.drop_column("item", "isbn10")
    op.drop_column("item", "thickness")
    op.drop_column("item", "width")
    op.drop_column("item", "location_id")
    op.drop_column("item", "dimensions")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "item",
        sa.Column("dimensions", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "item", sa.Column("location_id", sa.UUID(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "item",
        sa.Column(
            "width",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "item",
        sa.Column(
            "thickness",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "item", sa.Column("isbn10", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "item",
        sa.Column(
            "height",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_foreign_key(
        op.f("item_location_id_fkey"), "item", "item_location", ["location_id"], ["id"]
    )
    op.create_table(
        "item_location",
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "physical_location", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column("description", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("active", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "edited_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "deleted_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("created_by", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("edited_by", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("deleted_by", sa.UUID(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("item_location_pkey")),
    )
    # ### end Alembic commands ###
