"""Add location to item model

Revision ID: 0a9b2e8d9c86
Revises: fd76cc3e07e4
Create Date: 2026-02-11 08:44:47.060518

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "0a9b2e8d9c86"
down_revision: Union[str, None] = "fd76cc3e07e4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("collection_serie_fkey"), "collection", type_="foreignkey")
    op.drop_column("collection", "serie")
    op.add_column("item", sa.Column("location_id", sa.Uuid(), nullable=True))
    op.create_foreign_key(None, "item", "item_location", ["location_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "item", type_="foreignkey")
    op.drop_column("item", "location_id")
    op.add_column(
        "collection",
        sa.Column("serie", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        op.f("collection_serie_fkey"), "collection", "serie", ["serie"], ["id"]
    )
    # ### end Alembic commands ###
