extend type Query {
    getAuthors(params: GetAuthorsRequest): GetAuthorsResponse 
    getSeries: GetSerieResponse
}

extend type Mutation {
    createAuthor(author: CreateAuthorRequest): CreateAuthorResponse!
}


# Author schemas
input GetAuthorsRequest {
    authorId: Int
}

type GetAuthorsResponse {
    quantity: Int!
    authors: [Author]!
}

input CreateAuthorRequest {
    name: String!
    countryId: String
    languageId: String
    description: String
    isTranslator: Boolean = False
}

type CreateAuthorResponse  {
    author: Author!
}

type Author {
    authorId: ID!
    authorName: String!
    birthDate: String
    description: String
    countryId: String
    countryName: String
    languageId: String
    languageName: String
}

# Series schemas
type GetSerieResponse {
    quantity: Int!
    series: [Serie]
}

type Serie {
    serieId: String!
    serieName: String!
    description: String
    order: Int
    itemType: String
}