extend type Query {
    getAuthors(params: GetAuthorsRequest): GetAuthorsResponse 
}

extend type Mutation {
    createAuthor(author: CreateAuthorRequest): CreateAuthorResponse!
}

input GetAuthorsRequest {
    authorId: Int
}

type GetAuthorsResponse {
    quantity: Int!
    authors: [Author]!
}

input CreateAuthorRequest {
    name: String!
    countryId: String
    languageId: String
    description: String
    isTranslator: Boolean = False
}

type CreateAuthorResponse  {
    author: Author!
}


type Author {
    authorId: ID!
    authorName: String!
    birthDate: String
    description: String
    countryId: String
    countryName: String
    languageId: String
    languageName: String
}