extend type Query {
    getAuthors(params: GetAuthorsRequest): GetAuthorsResponse!
    getSeries: GetSerieResponse!
    getCollections: GetCollectionResponse!
    getPublishers: GetPublishersResponse!
    getLanguages: GetLanguagesResponse!
}

extend type Mutation {
    createAuthor(author: CreateAuthorRequest): CreateAuthorResponse!
    createSerie(serie: CreateSerieRequest): CreateSerieResponse!
    createCollection(collection: CreateCollectionRequest): CreateCollectionResponse!
    createPublisher(publihser: CreatePublisherRequest): CreatePublisherResponse!
    createLanguage(language: CreateLanguageRequest): CreateLanguageResponse!
}


# Author schemas
input GetAuthorsRequest {
    authorId: Int
}

type GetAuthorsResponse {
    quantity: Int!
    authors: [Author]!
}

input CreateAuthorRequest {
    name: String!
    countryId: String
    languageId: String
    description: String
    isTranslator: Boolean = False
}

type CreateAuthorResponse  {
    author: Author!
}

type Author {
    authorId: ID!
    authorName: String!
    birthDate: String
    description: String
    countryId: String
    countryName: String
    languageId: String
    languageName: String
}

# Series schemas
type GetSerieResponse {
    quantity: Int!
    series: [Serie]
}

input CreateSerieRequest {
    serieName: String!
}

type CreateSerieResponse {
    serie: Serie!
}

type Serie {
    serieId: String!
    serieName: String!
    description: String
    order: Int
    itemType: String
}

# Collections schemas
type GetCollectionResponse {
    quantity: Int!
    collections: [Collection]!
}

input CreateCollectionRequest {
    collectionsName: String!
    description: String
}

type CreateCollectionResponse {
    collection: Collection
}

type Collection {
    collectionId: ID!
    collectionName: String!
    description: String
}

# Publishers schemas
type GetPublishersResponse {
    quantity: Int!
    publishers: [Publisher]!
}

input CreatePublisherRequest {
    publisherName: String!
    countryId: String
    description: String
    parentId: Int
}

type CreatePublisherResponse {
    publisher: Publisher
}

type Publisher{
    publisherId: ID!
    publisherName: String!
    description: String
    countryId: String
    countryName: String
    parentId: Int
}

# Language schemas
type GetLanguagesResponse {
    quantity: Int!
    languages: [Language]!
}

input CreateLanguageRequest {
    languageId: String!
    languageName: String!
    languageCode: String!
}

type CreateLanguageResponse {
    language: Language!
}

type Language {
    languageId: String!
    languageName: String!
    languageCode: String
}