extend type Query {
  # Item queries
  getItem(id: Int!): Item
  getItems(params: GetItemInput): GetItemResponse
}

extend type Mutation {
    createItem(item: CreateItemInput!): CreateItemResponse!
}


# Item schemas
input GetItemInput {
  itemId: Int
  title: String
  mainAuthorId: Int
  itemType: String
}

type GetItemResponse {
    quantity: Int,
    items: [Item]
}

input CreateItemInput {
  lastStatusId: String!
  lastStatusDate: String!
  mainAuthorId: Int!
  otherAuthorsId: [Int]
  title: String!
  subtitle: String
  originalTitle: String
  originalSubtitle: String
  isbn: String
  isbn10: String
  itemTypeId: String
  pages: Int
  volume: Int
  edition: Int
  publicationDate: String
  originalPublicationDate: String
  serieId: Int
  collectionId: Int
  publisherId: Int
  formatId: String
  languageId: String
  coverPrice: Float
  paidPrice: Float
  dimensions: String
  hight: Int
  width: Int
  thickness: Int
  summary: String
  observation: String
  cover: String
}

type CreateItemResponse {
  item: Item
}

type Item {
  itemId: ID!
  mainAuthorId: Int!
  mainAuthorName: String
  title: String!
  subtitle: String
  titleOriginal: String
  subtitleOriginal: String
  isbn: String
  isbn10: String
  itemTypeId: String
  pages: Int
  volume: Int
  edition: Int
  publicationDate: String
  originalPublicationDate: String
  serieId: String
  serieName: String
  collectionId: String
  collectionName: String
  publisherId: String
  publisherName: String
  formatId: String
  languageId: String
  languageName: String
  coverPrice: Float
  paidPrice: Float

  lastStatusId: String
  lastStatusName: String
  lastStatusDate: String

  reading: Reading
}
