
extend type Query {
    # Reading queries
    getReading(reading_id: String!): GetReadingOutput!
    getReadings: GetReadingOutput!
    getActiveReadings: GetActiveReadingsOutput!
    getReadingProgress(params: GetReadingProgressInput): GetReadingProgressOutput!
    getReadingStats(params: GetReadingStatsInput): GetReadingStatsOutput!
}

extend type Mutation {
    # Reading mutations
    createReading(reading: CreateReadingInput!): CreateReadingOutput!
    createReadingProgress(progress: CreateReadingProgressInput!): CreateReadingProgressOutput!
}

# Base types
type Reading {
    id: String!
    itemId: Int!
    itemTitle: String
    item: Item!
    startDate: String!
    finishDate: String
    number: Int
    active: Boolean
    statusId: String
    statusName: String
}

type ReadingProgress {
    id: String!
    reading: Reading!
    date: String!
    page: Int
    percentage: Float
    rate: Int
    comment: String
}

# Input types (parameters)
input CreateReadingInput {
    itemId: Int!
    startDate: String!
    finishDate: String
    isDropped: Boolean = false
}

input GetReadingProgressInput {
    readingId: String!
}

input CreateReadingProgressInput {
    readingId: String!
    page: Int
    percentage: Int
    date: String
    rate: Int
    comment: String
}

input GetReadingStatsInput {
    itemId: Int!
}


# Output types (responses)
type GetReadingOutput {
    itemTitle: String!
    quantity: Int!
    readings: [Reading!]
}

type CreateReadingOutput {
    reading: Reading!
}

type GetReadingProgressOutput {
    quantity: Int!
    item: Item!
    itemTitle: String
    pagesRead: String
    progress: [ReadingProgress]!
}

type CreateReadingProgressOutput {
    item: Item!
    itemTitle: String!
    pagesRead: String
    progress: ReadingProgress!
}

type GetActiveReadingsOutput {
    quantity: Int!
    readings: [Reading]!
}

type GetReadingStatsOutput {
    item: Item!
    itemTitle: String!
    readingsCount: Int!
    currentReading: Reading
    currentPage: Int
}