
extend type Query {
    # Reading queries
    getReading(reading_id: String!): GetReadingOutput!
    getReadings: GetReadingOutput!
    getActiveReadings: GetActiveReadingsOutput!
    getReadingProgress(params: GetReadingProgressInput): GetReadingProgressOutput!
    getReadingStats(params: GetReadingStatsInput): GetReadingStatsOutput!
}

extend type Mutation {
    # Reading mutations
    createReading(reading: CreateReadingInput!): CreateReadingOutput!
    createReadingProgress(progress: CreateReadingProgressInput!): CreateReadingProgressOutput!
}

# Base types
type Reading {
    id: String!
    item_id: Int!
    item_title: String
    item: Item!
    start_date: String!
    finish_date: String
    number: Int
    active: Boolean
    status_id: String
    status_name: String
}

type ReadingProgress {
    id: String!
    reading: Reading!
    date: String!
    page: Int
    percentage: Float
    rate: Int
    comment: String
}

# Input types (parameters)
input CreateReadingInput {
    item_id: Int!
    start_date: String!
    finish_date: String
    is_dropped: Boolean = false
}

input GetReadingProgressInput {
    reading_id: String!
}

input CreateReadingProgressInput {
    reading_id: String!
    page: Int
    percentage: Int
    date: String
    rate: Int
    comment: String
}

input GetReadingStatsInput {
    item_id: Int!
}


# Output types (responses)
type GetReadingOutput {
    item_title: String!
    quantity: Int!
    readings: [Reading!]
}

type CreateReadingOutput {
    reading: Reading!
}

type GetReadingProgressOutput {
    quantity: Int!
    item: Item!
    item_title: String
    pages_read: String
    progress: [ReadingProgress]!
}

type CreateReadingProgressOutput {
    item: Item!
    item_title: String!
    pages_read: String
    progress: ReadingProgress!
}

type GetActiveReadingsOutput {
    quantity: Int!
    readings: [Reading]!
}

type GetReadingStatsOutput {
    item: Item!
    item_title: String!
    readings_count: Int!
    current_reading: Reading
    current_page: Int
}