type CreateReadingResponse {
  reading: Reading!
}

type Reading {
  id: String!
  item_id: Int!
  item_title: String
  item: Item!
  start_date: String!
  finish_date: String
  number: Int
  active: Boolean
  status_id: String
  status_name: String
}

input ReadingInput {
  item_id: Int!
  start_date: String!
  finish_date: String
  is_dropped: Boolean = false
}

type ReadingOutput {
  item_title: String!
  quantity: Int!
  readings: [Reading!]
}

type ReadingProgress {
  id: String!
  reading: Reading!
  date: String!
  page: Int
  percentage: Float
  rate: Int
  comment: String
}

input GetReadingProgress {
  reading_id: String!
}

input ReadingProgressInput {
  reading_id: String!
  page: Int
  percentage: Int
  date: String
  rate: Int
  comment: String
}

type ReadingProgressOutput {
  quantity: Int!
  item: Item!
  item_title: String
  pages_read: Int
  progress: [ReadingProgress]!
}

type GetReadingProgresOutput {
  item_title: String!
  pages_read: String
  progress: ReadingProgress!
}